Repository Zanzigzan/CPSC-2350-group-project, pull requests merged in 2024-04, with the labels that each got.

#137 fixed layout of page 2 #136
  fluentify/src/SecondPage.jsx
  fluentify/src/components/QuizDisplay.jsx
Labels: enhancement

#144 made Page 2 layout consistent with Main page
  fluentify/src/SecondPage.jsx
  fluentify/src/components/MainHeader.jsx
  fluentify/src/components/TranslatedText.jsx
  fluentify/src/fonts/Bumbbled.otf
  fluentify/src/fonts/MuseoSansRounded500.otf
  fluentify/tailwind.config.js
Labels: enhancement

#153 Add modal for files that are less than 10 words
  fluentify/src/App.test.jsx
  fluentify/src/api/getTextFromFile.js
  fluentify/src/components/MainPageModal.jsx
  fluentify/src/components/SelectFile.test.jsx
  fluentify/src/context/LanguageContext.jsx
  fluentify/vite.config.js
Labels: enhancement

#191 add integration tests for detecting language #160
  fluentify/src/App.test.jsx
  fluentify/src/components/SelectFile.test.jsx
Labels: integration-test

#192 Update README and add License
  LICENSE
  README.md
  fluentify/README.md
Labels: documentation

#196 Unit tests for generateText added
  fluentify/src/api/openai.test.js
Labels: unit-test

#198 AI declaration forms added for Project Milestone 2
  AI Usage Declaration Forms/Project Milestone #2/P2_AI_Declaration_Isabelle_Wang_100396670.pdf
  AI Usage Declaration Forms/Project Milestone #2/P2_AI_Declaration_Pawel_Michalski_100390068.pdf
  AI Usage Declaration Forms/Project Milestone #2/P2_AI_Declaration_Shushama_Tahsin_100274844.pdf
  AI Usage Declaration Forms/Project Milestone #2/P2_AI_Declaration_Van_Valdez_100390120.pdf
Labels: documentation
